@baseURL = http://localhost:3333
@authToken = {{sing_in.response.body.token}}
@questionId = {{fetch_recent_question.response.body.questions[0].id}}

###

# @name sing_up
POST {{baseURL}}/sing-up
Content-Type: application/json

{
  "name": "John Doe",
  "email": "JohnDoe@example.com",
  "password": "12345678"
}

###

# @name sing_in
POST {{baseURL}}/sing-in
Content-Type: application/json

{
  "email": "JohnDoe@example.com",
  "password": "12345678"
}

###

# @name create_question
POST {{baseURL}}/question
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "new question 7",
  "content": "content of question",
  "attachmentsId": []
}

###

# @name fetch_recent_question
GET  {{baseURL}}/question?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug
GET  {{baseURL}}/question/new Question 7
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
POST   {{baseURL}}/question/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "edited question",
  "content": "edited content",
  "attachmentsId": []
}

